[[trees]]
root = "./repos"

  [[trees.repos]]
  name = "public/postgres"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/postgres/postgres.git"
    type = "https"

  [[trees.repos]]
  name = "public/pgbouncer"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/pgbouncer/pgbouncer.git"
    type = "https"

  [[trees.repos]]
  name = "public/pg_partman"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/pgpartman/pg_partman.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/vault"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/vault.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/pg_net"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/pg_net.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/supabase"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/supabase.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/wrappers"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/wrappers.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/postgres"

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/postgres.git"
    type = "https"
