[[trees]]
root = "./repos"

  # Public repos
  [[trees.repos]]
  name = "public/postgres"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/postgres/postgres.git"
    type = "https"

  [[trees.repos]]
  name = "public/pgbouncer"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/pgbouncer/pgbouncer.git"
    type = "https"

  [[trees.repos]]
  name = "public/pg_partman"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/pgpartman/pg_partman.git"
    type = "https"

  # Supabase repos
  # TODO May need to move to ~/supabase per security docs
  [[trees.repos]]
  name = "supabase/vault"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/vault.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/pg_net"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/pg_net.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/supabase"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/supabase.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/wrappers"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/wrappers.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/postgres"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/postgres.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/supautils"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/supautils.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/pg_jsonschema"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/pg_jsonschema.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/pg_graphql"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/supabase/pg_graphql.git"
    type = "https"

  [[trees.repos]]
  name = "supabase/index_advisor"
  worktree_setup = true

    [[trees.repos.remotes]]
    name = "origin"
    url = "https://github.com/olirice/index_advisor.git"
    type = "https"
